/*
Exercise 19: (2) Repair the problem in LostMessage.java
by guarding the call in the finally clause.
 */
import exceptions.LostMessage;

public class Exercise19 {
    public static void main(String[] args){
        LostMessage.main(args);
    }
}
